name: agperils-amp
channels:
  - conda-forge
  - defaults
dependencies:
  - python  # cur: 3.10.4
  - ipykernel  # jupyter nb  # cur: 6.11.0
  - ipywidgets  # jupyter nb  # cur: 7.7.0
  - pandas  # cur: 1.4.1
  - pip  # cur: 22.0.4
  - poppler  # dep(pdf2image)  # cur: 22.01.0
  - pytesseract  # conda > pip  # cur: 0.3.10
  - pip:
    - black[jupyter]  # cur: 22.3.0
    - dateparser  # cur: 1.1.1
    - pdf2image  # pip > conda  # cur: 1.16.0
    - requests  # cur: 2.27.1
