name: agperils-amp
channels:
  - conda-forge
  - defaults
dependencies:
  - python  # cur: 3.10.4
  - distro  # dep(tabula-py)
  - ipykernel  # jupyter nb
  - ipywidgets  # jupyter nb
  - numpy >= 1.23.3
  - ocrmypdf >= 14.0.1
  - pandas >= 1.5.1
  - pdfplumber >= 0.7.5
  - pdftotext >= 2.2.2
  - pip
  - poppler >= 22.10.0  # dep(pdf2image)
  - pytesseract >= 0.3.10
  - requests >= 2.28.1
  - pip:
    - black[jupyter] >= 22.10.0
    - dateparser >= 1.1.1
    - pandera[io] >= 0.13.2
    - pdf2image >= 1.16.0  # pdf2image
    - tabula-py  # tabula-py
